spring.application.name=demo
# 1. Database Connection Configuration
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/sadiki}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:yusuph}

# 2. JPA / Hibernate Properties
# ddl-auto=update inatengeneza majedwali kiotomatiki kwenye Postgres kulingana na kodi zako za Java!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 3. Thymeleaf Cache (Zima wakati wa kutengeneza mfumo ili ukibadili HTML uone mabadiliko haraka)
spring.thymeleaf.cache=false

server.port=${PORT:8080}